[build]
  command = "npm run build"
  publish = "dist"
  environment = { GEMINI_API_KEY = "GEMINI_API_KEY" }

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"